server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://172.16.21.134:5432/postmonitoring
    password: 0sEps3bP3RdXkRs7q
    username: postgres

8005:
  connection-db:
#    url: jdbc:postgresql://localhost:5432/7005
    url: jdbc:postgresql://172.16.21.134:5432/7005
    username: postgres
    password: 0sEps3bP3RdXkRs7q
    driver: org.postgresql.Driver
