springdoc:
  packages-to-scan: com.pos.monitoring.controller
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
       path : /api-docs
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 0
      maximumPoolSize: 15
      idleTimeout: 30000000
      maxLifetime: 60000000
      leakDetectionThreshold: 18000000
      connectionTimeout: 120000000
      transaction-isolation: 2
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    open-in-view: true
  main:
    lazy-initialization: false
# jwt configuration elements
jwt:
  expire: 86400000
  refresh_expire: 864000000
  secret: 'gfhg4561967$%#%$%^?>?>:gjhgsdfsd?>jahdqpdsdfgsdfgqweg143635783579821wefgafnherythgwbsbssdhgf'
  issuer_access: 'Men1ng $eviml1 0yinim Asph@ltasnaksdfgkjlabsdkg avkljqh asdkghalsnd vlkashdfglan sdf.gqw;sdfhg;arpgf;aklnsdbqiupwehtp1qg'
  issuer_refresh: 'Uzc@rd b1rinch1 t0l0v tizasdfhgasdfghwejundb rtgjhwvb4yujbur4red6ur7,llt,mrfgyuol1mi'

pos:
  monitoring:
    user:
      username: sysAdmin
      password: qwedyetyer123124_=
    login:
      url: http://localhost:8080/api/authenticate