server:
  port: 9005


spring:
  datasource:
    password: 0sEps3bP3RdXkRs7q
    username: postgres
    url: jdbc:postgresql://172.17.119.4:6070/postmonitoring
8005:
  connection-db:
    url: jdbc:postgresql://172.17.119.4:6070/7005
    username: postgres
    password: 0sEps3bP3RdXkRs7q
    driver: org.postgresql.Driver
