package com.pos.monitoring.exceptions;

public enum ErrorCode {

    ENTITY_NOT_FOUND,
    SERVER_ERROR_FROM8005,
    URL_NOT_FOUND,
    UN_AUTHORIZED,
    MISSING_REQUIRED_FIELD,
    MISSING_REQUIRED_FILE,
    VALIDATION_ERROR,
    PARAMETER_NOT_FOUND,
    FIELD_VALUE_UNIQUE,
    REQUIRED_FIELD,
    VALUE_DID_NOT_MATCH,
    USERNAME_NOT_FOUND;
}
